config/routes.rb
Roly::Application.routes.draw do
  get "user/init_users"
  get "user/init_user_rolies"
  get "user/assign_rolies_to_user"
  devise_for :users , :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get '/users/sign_up_mobile' => 'registrations#new_mobile'
  end

  get "admin/search_preferences"

  get "admin/privacy_preferences"

  get "admin/account"

  get "admin/edit_account"
  match "/admin/switch_user/:user_id" => "admin#switch_user"

  match "app_info" => "admin#app_info"

  match '/businesses/view/:business_id' => "businesses#view_business"
  match '/businesses/add/:business_id' => "businesses#add"
  match '/businesses/new' => "businesses#new"
  match "/businesses/my" => "businesses#show"

  resources :my_roly_cards

  match '/albums/edit/:album_id' => "albums#edit_album"
  match '/albums/view/:album_id' => "albums#view_album"
  match '/albums/add/:album_id' => "albums#add"
  match '/albums/new' => "albums#new"
  match "/albums/my" => "albums#show"
  match "/albums/favorites" => "albums#favorite"
  match "/albums/recent" => "albums#recent"
  match "/albums/recently_added" => "albums#recently_added"
  match "/albums/today" => "albums#today"

  get "roly/search"
  match '/r/cbc/:share_code' => "roly#card_by_code"
  match '/roly/card_by_location/:share_code' => "roly#get_card"
  match '/roly/get_card' => "roly#get_card"
  match '/roly/:roly_id' => "roly#detail"
  match '/roly/share/:roly_id' => "roly#share"

  get "roly/map"

  match '/qr' => "roly#qrcode"
  match '/' => "albums#recent"

  root :to => 'my_roly_cards#index'

end

app/controllers/my_roly_cards_controller.rb
class MyRolyCardsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @rolies = RolyCard.findByUser(current_user)
  end

  def show
    @roly = RolyCard.find(params[:id])
  end

  def new
    @new_roly_form = RolyCard.new
  end

  def create
    @roly = RolyCard.new(params[:roly_card])
    @roly.user = current_user
    if @roly.save
      redirect_to my_roly_cards_path(@roly)
    else
      redirect_to action: :new
    end
  end

  def share
    @roly = RolyCard.findByIdUser(params[:roly_id],@user)
    @roly.share_code = "456F34"
    @roly.share_date = DateTime.now()
    @roly.save
  end

  def update
    @roly = RolyCard.find(params[:id])
    @roly.update_attributes(params[:roly_card])
    @roly.save
    redirect_to action: :show
  end

  def edit
    if (request.get?)
      @roly = RolyCard.find(params[:roly_id])
      @edit_roly_form = EditRolyForm.new(@roly)
    else
      @roly = RolyCard.find(params[:roly_id])
      @roly.update_attributes(params[:edit_roly_form])
      @edit_roly_form = EditRolyForm.new(@roly)
      @roly.save
      redirect_to "/my_roly_cards/view/"+@roly.id.to_s
    end
    @roly = RolyCard.find(params[:id])
  end

  def destroy
    @roly = RolyCard.find(params[:id])
    @roly.destroy
    redirect_to action: :index
  end

end

app/helpers/my_roly_cards_helper.rb
module MyRolyCardsHelper
end

app/views/my_roly_cards/edit.html.erb
<div>
	Share
</div>
	<%= form_for @roly , multipart: true, url: my_roly_card_path, :html => {:id => 'submit_form',:multipart => true}, :method => :put do |f| %>
<%= f.file_field  :photo %>
<div><%= image_tag @roly.photo.url(:medium), :style => "width:300px;padding:10px;vertical-align:middle" %>
</div>
<div>
	<%= f.text_field :title, html_options = {:id => 'title', :size => '20', :placeholder => 'Name'} %>
	<br>
	<%= f.text_field :address, html_options = {:id => 'address', :size => '20', :placeholder => 'Address'} %>
</div>

<div>
	<%= f.text_area :description, html_options = {:id => 'title', :cols => '35', :rows => '10', :placeholder => 'Description'} %>
</div>


<hr>
<table style="border:1px #70b8ff dashed;width:300px">
	<tr>
		<td style="border:1px #70b8ff dashed">
		<div style="text-align:center">
			<%= f.text_field :web_page, html_options = {:id => 'web_page', :size => '20', :placeholder => 'Web Page'} %>
		</div></td>
		<td style="border:1px #70b8ff dashed">
</td>
</tr>
</table>
<hr>

<img src="http://midcitymessenger.com/wp-content/uploads/2013/08/13_8_12restaurantmap.jpg" width="300" height="250">

<hr>

<table style="border:1px #70b8ff dashed;height:50px;width:300px">
	<tbody>
		<tr>
			<td style="border:1px #70b8ff dashed">
			<div>
	<%= f.text_field :telephone, html_options = {:id => 'email', :size => '15', :placeholder => 'Telephone'} %>
			</div></td>
			<td style="border:1px #70b8ff dashed;text-align:right">
			<div>
	<%= f.text_field :email, html_options = {:id => 'web_page', :size => '15', :placeholder => 'Email'} %>
			</div></td>
		</tr>
	</tbody>
</table>

<hr>
  	<%= submit_tag("Update") %>
	<% end %>

app/views/my_roly_cards/index.html.erb
<div class="title">
  <h2>My Rolies</h1>
</div>
<p>
  <a href="/my_roly_cards/new">New Roly</a>
</p>

<div>Unassigned Business</div>
<table>
	<% @rolies.each do |roly| %>
	<tr>
		<td><%= link_to (image_tag roly.photo.url(:thumb), :style => "width:50px;padding:10px;vertical-align:middle"), my_roly_card_path(roly) %></td>
		<td><%= link_to roly.title, my_roly_card_path(roly) %><br />
            <%= roly.address %><br />
			<% if !roly.twitter.nil? %>
			<img src="/images/thumb/twitter.png" width="16" height="16">
			<% end %>
			<% if !roly.facebook.nil? %>
			<img src="/images/thumb/facebook.png" width="16" height="16">
			<% end %>
			<% if !roly.foursquare.nil? %>
			<img src="/images/thumb/foursquare.png" width="16" height="16">
			<% end %>
			<% if !roly.google.nil? %>
			<img src="/images/thumb/map.png" width="16" height="16">
			<% end %>
		</td>
		<td></td>
	</tr>
	<% end %>
</table>
<div>Fomento Geek</div>
<table>
	<% @rolies.each do |roly| %>
	<tr>
		<td><%= link_to (image_tag roly.photo.url(:thumb), :style => "width:50px;padding:10px;vertical-align:middle"), my_roly_card_path(roly) %>
		<td><%= link_to roly.title, my_roly_card_path(roly) %><br />
            <%= roly.address %><br />
			<img src="/images/thumb/twitter.png" width="16" height="16">
			<img src="/images/thumb/facebook.png" width="16" height="16">
			<img src="/images/thumb/foursquare.png" width="16" height="16">
			<img src="/images/thumb/map.png" width="16" height="16">
		</td>
		<td></td>
	</tr>
	<% end %>
</table>

app/views/my_roly_cards/new.html.erb
<div class="row-fluid">
  <div class="title col-xs-12">
	 <h2>New Roly Card</h2>
  </div>
	<%= form_for @new_roly_form , url: my_roly_cards_path, :html => {:id => 'submit_form', :role => "form", :class => 'form-horizontal'}, :method => :post do |f| %>
  <div class="form-group">
	 <label for="title" class="col-xs-3 control-label">
    Title
   </label>
   <div class="col-xs-9 col-lg-6">
    <%= f.text_field :title, html_options = {:id => 'title', :size => '20', :placeholder => 'Title', :class => 'form-control'} %>
   </div>
  </div>
  <div class="form-group">
   <label for="adress" class="col-xs-3 control-label">
    Adress
   </label>
   <div class="col-xs-9 col-lg-6">
	  <%= f.text_field :address, html_options = {:id => 'address', :size => '20', :placeholder => 'Address', :class => 'form-control'} %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-xs-12 center">
    <%= submit_tag "Create", html_options = {:class => 'btn btn-default'} %>
   </div>
  </div>
	<% end %>
</div>

app/views/my_roly_cards/share.html.erb
<div><a href="/my_roly_cards/view/<%= @roly.id %>">Back to roly</a></div>
<div></div>
<div><%= image_tag @roly.photo.url(:thumb), :style => "width:100px;padding:10px;vertical-align:middle" %>
</div>
<div>
	<%= @roly.title %>
	<br>
</div>

<div>
	<%= @roly.address %>
</div>
<div style="text-align: center;font-size: 24pt">
	<%= @roly.share_code %>
</div>
<div>
	<img src="/qr.jpg?url=http://roly.dnsdojo.com:3000/r/cbc/<%= @roly.share_code %>"  width="300px"/>
</div>

<hr>
<div>
	email roly	
</div>
<div>
	Make available in area
	<select>
		<option>1 minute</option>
		<option>5 minutes</option>
		<option>10 minutes</option>
		<option>1 hour</option>
		<option>12 hours</option>
		<option>1 day</option>
		<option>1 year</option>
		<option>Indefinately</option>
	</select>
</div>

app/views/my_roly_cards/show.html.erb
<div class="title">
  <h3> <%= @roly.title %></h3>
</div>
<div class="row-fluid">
  <div class="col-xs-4">
    <a href="/my_roly_cards/share/<%= @roly.id %>" class="btn btn-default">Share</a>
  </div>
  <div class="col-xs-4">
    <%= link_to "Edit", edit_my_roly_card_path(@roly), :class => 'btn btn-default' %>
  </div>
  <div class="col-xs-4">
    <%= link_to "Delete", my_roly_card_path(@roly), :method => :delete, :class => 'btn btn-danger' %>
  </div>
</div>
<div class="row-fluid">
  <%= image_tag @roly.photo.url(:medium), :style => "width:300px;padding:10px;vertical-align:middle" %>
</div>
<div>
	Business Unassigned
</div>
<div>
	<%= @roly.title %>
	<br>
	<%= @roly.address %>
</div>

<div>
	<%= @roly.description %>
</div>

<hr>
<table style="border:1px #70b8ff dashed;width:300px">
	<tr>
		<td style="border:1px #70b8ff dashed">
		<div style="text-align:center">
			<%= @roly.web_page %>
		</div></td>
		<td style="border:1px #70b8ff dashed">
		<table style="border:1px #70b8ff dashed">
			<tbody>
				<tr>
					<td>
					<div><img src="http://www.iessantafe.edu.ar/iesweb/img/facebook-icon.png">
					</div><td>
					<div>
						<%= @roly.facebook %> 3
					</div></td>
					<td>
					<div>
						likes
					</div></td>
		</td>
	</tr>
	</tbody>
</table>
</td>
<td style="border:1px #70b8ff dashed">
<table style="border:1px #70b8ff dashed">
	<tbody>
		<tr>
			<td>
			<div><img src="http://bleachtree.com/images/twitter_icon.png">
			</div><td>
			<div>
				<%= @roly.twitter %> 98
			</div></td>
			<td>
			<div>
				followers
			</div></td>
</td></tr>
</tbody>
</table>
</td>
</tr>
</table>
<hr>

<img src="http://midcitymessenger.com/wp-content/uploads/2013/08/13_8_12restaurantmap.jpg" width="300" height="250">

<hr>

<table style="border:1px #70b8ff dashed;height:50px;width:300px">
	<tbody>
		<tr>
			<td style="border:1px #70b8ff dashed">
			<div>
				<img src="https://cdn1.iconfinder.com/data/icons/metro-uinvert-dock/256/Phone.png" width="50" height="50">
				<%= @roly.telephone %>
			</div></td>
			<td style="border:1px #70b8ff dashed;text-align:right">
			<div>
				<input type="button" value="Email">
				<%= @roly.email %>
			</div></td>
		</tr>
	</tbody>
</table>

<hr>

app/views/my_roly_cards/view.html.erb
<div><a href="/my_roly_cards/share/<%= @roly.id %>">Share</a></div>
<div><a href="/my_roly_cards/edit/<%= @roly.id %>">Edit</a></div>
<div><%= image_tag @roly.photo.url(:medium), :style => "width:300px;padding:10px;vertical-align:middle" %>
</div>
<div>
	<select>
		<option>Private</option>
		<option>Public</option>>
		
	</select>
</div>
<div>
	<%= @roly.title %>
	<br>
	<%= @roly.address %>
</div>

<div>
	<%= @roly.description %>
</div>

<hr>
<table style="border:1px #70b8ff dashed;width:300px">
	<tr>
		<td style="border:1px #70b8ff dashed">
		<div style="text-align:center">
			<%= @roly.web_page %>
		</div></td>
		<td style="border:1px #70b8ff dashed">
		<table style="border:1px #70b8ff dashed">
			<tbody>
				<tr>
					<td>
					<div><img src="http://www.iessantafe.edu.ar/iesweb/img/facebook-icon.png">
					</div><td>
					<div>
						<%= @roly.facebook %> 3
					</div></td>
					<td>
					<div>
						likes
					</div></td>
		</td>
	</tr>
	</tbody>
</table>
</td>
<td style="border:1px #70b8ff dashed">
<table style="border:1px #70b8ff dashed">
	<tbody>
		<tr>
			<td>
			<div><img src="http://bleachtree.com/images/twitter_icon.png">
			</div><td>
			<div>
				<%= @roly.twitter %> 98
			</div></td>
			<td>
			<div>
				followers
			</div></td>
</td></tr>
</tbody>
</table>
</td>
</tr>
</table>
<hr>

<img src="http://midcitymessenger.com/wp-content/uploads/2013/08/13_8_12restaurantmap.jpg" width="300" height="250">

<hr>

<table style="border:1px #70b8ff dashed;height:50px;width:300px">
	<tbody>
		<tr>
			<td style="border:1px #70b8ff dashed">
			<div>
				<img src="https://cdn1.iconfinder.com/data/icons/metro-uinvert-dock/256/Phone.png" width="50" height="50">
				<%= @roly.telephone %>
			</div></td>
			<td style="border:1px #70b8ff dashed;text-align:right">
			<div>
				<input type="button" value="Email">
				<%= @roly.email %>
			</div></td>
		</tr>
	</tbody>
</table>

<hr>