config/routes.rb
Roly::Application.routes.draw do
  get "user/init_users"
  get "user/init_user_rolies"
  get "user/assign_rolies_to_user"
  devise_for :users , :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get '/users/sign_up_mobile' => 'registrations#new_mobile'
  end

  get "admin/search_preferences"

  get "admin/privacy_preferences"

  get "admin/account"

  get "admin/edit_account"
  match "/admin/switch_user/:user_id" => "admin#switch_user"

  match "app_info" => "admin#app_info"

  match '/businesses/view/:business_id' => "businesses#view_business"
  match '/businesses/add/:business_id' => "businesses#add"
  match '/businesses/new' => "businesses#new"
  match "/businesses/my" => "businesses#show"

  resources :my_roly_cards

  match '/albums/edit/:album_id' => "albums#edit_album"
  match '/albums/view/:album_id' => "albums#view_album"
  match '/albums/add/:album_id' => "albums#add"
  match '/albums/new' => "albums#new"
  match "/albums/my" => "albums#show"
  match "/albums/favorites" => "albums#favorite"
  match "/albums/recent" => "albums#recent"
  match "/albums/recently_added" => "albums#recently_added"
  match "/albums/today" => "albums#today"

  get "roly/search"
  match '/r/cbc/:share_code' => "roly#card_by_code"
  match '/roly/card_by_location/:share_code' => "roly#get_card"
  match '/roly/get_card' => "roly#get_card"
  match '/roly/:roly_id' => "roly#detail"
  match '/roly/share/:roly_id' => "roly#share"

  get "roly/map"

  match '/qr' => "roly#qrcode"
  match '/' => "albums#recent"

  root :to => 'my_roly_cards#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Roly MKI</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div>
			<div style="border:1px #70b8ff dashed;height:900px;width:300px">
        <table style="border:1px #70b8ff dashed;width:300px">
            <tr>
                <td style="border:1px #70b8ff dashed"><div style="text-align:center"><a href="/">Home</a></div></td>
                <td style="border:1px #70b8ff dashed"><div style="text-align:center"><a href="/my_roly_cards/my">My Roly</a></div></td>
                <td style="border:1px #70b8ff dashed"><div style="text-align:center"><a href="/logout">Logout</a></div></td>
            </tr>
        </table>
				<%= yield %>


			</div>
		</div>
		<div style="border:1px #70b8ff dashed;width:300px">
			<p style="text-align: center">
					2013 roly
				</p>

		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roly MKI</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <p class="navbar-toggle pull-right">
         <%- if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger' %>
         <%- else %>
          <%= link_to "Login", new_user_session_path, :method => :delete, :class => 'btn btn-primary' %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-info' %>
         <%- end %>
       </p>
       <a class="navbar-brand" href="#">Roly</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <p class="navbar-text pull-right">
          <%- if user_signed_in? %>
            Login as <%= current_user.email %> &nbsp;
            <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
          <%- else %>
            <%= link_to "Login", new_user_session_path %> &nbsp;
            <%= link_to "Sign up", new_user_registration_path %>
          <%- end %>
        </p>
      </div><!-- /.navbar-collapse -->
    </nav>
    <div class="row-fluid">
      <div class="col-xs-4 col-md-2 btn btn-default">
        <%= link_to "Search", '/roly/search' %>
      </div>
      <div class="col-xs-4 col-md-2 btn btn-default">
        <%= link_to "My Rolies", my_roly_cards_path %>
      </div>
      <div class="col-xs-4 col-md-2 btn btn-default">
        <%= link_to "Get Roly", '/roly/get_card' %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-xs-4 col-md-2 btn btn-default">
        <%= link_to "Recent", '/albums/recently_added' %>
      </div>
      <div class="col-xs-4 col-md-2 btn btn-default">
        <%= link_to "Favorites", '/albums/favorites' %>
      </div>
      <div class="col-xs-4 col-md-2 btn btn-default">
        <%= link_to "Today's", '/albums/today' %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-xs-12">
        <%= yield %>
      </div>
    </div>
    <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
      <div class="center">
        <a href="/admin/account">Profile</a> 2013 roly
      </div>
    </nav>
  </div> <!-- container-fluid -->
</body>
</html>